// ISO 3166-1 alpha-2 country code -> { name, currency (ISO 4217), locale, flag emoji }
export interface CountryInfo {
  code: string;
  name: string;
  currency: string;
  locale: string;
  flag: string;
}

const cc = (code: string) =>
  code
    .toUpperCase()
    .split('')
    .map((c) => String.fromCodePoint(127397 + c.charCodeAt(0)))
    .join('');

const raw: Array<[string, string, string, string]> = [
  // [code, name, currency, locale]
  ['AD', 'Andorra', 'EUR', 'ca-AD'],
  ['AE', 'United Arab Emirates', 'AED', 'ar-AE'],
  ['AF', 'Afghanistan', 'AFN', 'fa-AF'],
  ['AG', 'Antigua and Barbuda', 'XCD', 'en-AG'],
  ['AI', 'Anguilla', 'XCD', 'en-AI'],
  ['AL', 'Albania', 'ALL', 'sq-AL'],
  ['AM', 'Armenia', 'AMD', 'hy-AM'],
  ['AO', 'Angola', 'AOA', 'pt-AO'],
  ['AR', 'Argentina', 'ARS', 'es-AR'],
  ['AS', 'American Samoa', 'USD', 'en-AS'],
  ['AT', 'Austria', 'EUR', 'de-AT'],
  ['AU', 'Australia', 'AUD', 'en-AU'],
  ['AW', 'Aruba', 'AWG', 'nl-AW'],
  ['AX', 'Åland Islands', 'EUR', 'sv-AX'],
  ['AZ', 'Azerbaijan', 'AZN', 'az-AZ'],
  ['BA', 'Bosnia and Herzegovina', 'BAM', 'bs-BA'],
  ['BB', 'Barbados', 'BBD', 'en-BB'],
  ['BD', 'Bangladesh', 'BDT', 'bn-BD'],
  ['BE', 'Belgium', 'EUR', 'nl-BE'],
  ['BF', 'Burkina Faso', 'XOF', 'fr-BF'],
  ['BG', 'Bulgaria', 'BGN', 'bg-BG'],
  ['BH', 'Bahrain', 'BHD', 'ar-BH'],
  ['BI', 'Burundi', 'BIF', 'fr-BI'],
  ['BJ', 'Benin', 'XOF', 'fr-BJ'],
  ['BL', 'Saint Barthélemy', 'EUR', 'fr-BL'],
  ['BM', 'Bermuda', 'BMD', 'en-BM'],
  ['BN', 'Brunei', 'BND', 'ms-BN'],
  ['BO', 'Bolivia', 'BOB', 'es-BO'],
  ['BQ', 'Caribbean Netherlands', 'USD', 'nl-BQ'],
  ['BR', 'Brazil', 'BRL', 'pt-BR'],
  ['BS', 'Bahamas', 'BSD', 'en-BS'],
  ['BT', 'Bhutan', 'BTN', 'dz-BT'],
  ['BW', 'Botswana', 'BWP', 'en-BW'],
  ['BY', 'Belarus', 'BYN', 'be-BY'],
  ['BZ', 'Belize', 'BZD', 'en-BZ'],
  ['CA', 'Canada', 'CAD', 'en-CA'],
  ['CC', 'Cocos (Keeling) Islands', 'AUD', 'en-CC'],
  ['CD', 'DR Congo', 'CDF', 'fr-CD'],
  ['CF', 'Central African Republic', 'XAF', 'fr-CF'],
  ['CG', 'Republic of the Congo', 'XAF', 'fr-CG'],
  ['CH', 'Switzerland', 'CHF', 'de-CH'],
  ['CI', 'Côte d’Ivoire', 'XOF', 'fr-CI'],
  ['CK', 'Cook Islands', 'NZD', 'en-CK'],
  ['CL', 'Chile', 'CLP', 'es-CL'],
  ['CM', 'Cameroon', 'XAF', 'fr-CM'],
  ['CN', 'China', 'CNY', 'zh-CN'],
  ['CO', 'Colombia', 'COP', 'es-CO'],
  ['CR', 'Costa Rica', 'CRC', 'es-CR'],
  ['CU', 'Cuba', 'CUP', 'es-CU'],
  ['CV', 'Cape Verde', 'CVE', 'pt-CV'],
  ['CW', 'Curaçao', 'ANG', 'nl-CW'],
  ['CX', 'Christmas Island', 'AUD', 'en-CX'],
  ['CY', 'Cyprus', 'EUR', 'el-CY'],
  ['CZ', 'Czechia', 'CZK', 'cs-CZ'],
  ['DE', 'Germany', 'EUR', 'de-DE'],
  ['DJ', 'Djibouti', 'DJF', 'fr-DJ'],
  ['DK', 'Denmark', 'DKK', 'da-DK'],
  ['DM', 'Dominica', 'XCD', 'en-DM'],
  ['DO', 'Dominican Republic', 'DOP', 'es-DO'],
  ['DZ', 'Algeria', 'DZD', 'ar-DZ'],
  ['EC', 'Ecuador', 'USD', 'es-EC'],
  ['EE', 'Estonia', 'EUR', 'et-EE'],
  ['EG', 'Egypt', 'EGP', 'ar-EG'],
  ['EH', 'Western Sahara', 'MAD', 'ar-EH'],
  ['ER', 'Eritrea', 'ERN', 'ti-ER'],
  ['ES', 'Spain', 'EUR', 'es-ES'],
  ['ET', 'Ethiopia', 'ETB', 'am-ET'],
  ['FI', 'Finland', 'EUR', 'fi-FI'],
  ['FJ', 'Fiji', 'FJD', 'en-FJ'],
  ['FK', 'Falkland Islands', 'FKP', 'en-FK'],
  ['FM', 'Micronesia', 'USD', 'en-FM'],
  ['FO', 'Faroe Islands', 'DKK', 'fo-FO'],
  ['FR', 'France', 'EUR', 'fr-FR'],
  ['GA', 'Gabon', 'XAF', 'fr-GA'],
  ['GB', 'United Kingdom', 'GBP', 'en-GB'],
  ['GD', 'Grenada', 'XCD', 'en-GD'],
  ['GE', 'Georgia', 'GEL', 'ka-GE'],
  ['GF', 'French Guiana', 'EUR', 'fr-GF'],
  ['GG', 'Guernsey', 'GBP', 'en-GG'],
  ['GH', 'Ghana', 'GHS', 'en-GH'],
  ['GI', 'Gibraltar', 'GIP', 'en-GI'],
  ['GL', 'Greenland', 'DKK', 'kl-GL'],
  ['GM', 'Gambia', 'GMD', 'en-GM'],
  ['GN', 'Guinea', 'GNF', 'fr-GN'],
  ['GP', 'Guadeloupe', 'EUR', 'fr-GP'],
  ['GQ', 'Equatorial Guinea', 'XAF', 'es-GQ'],
  ['GR', 'Greece', 'EUR', 'el-GR'],
  ['GT', 'Guatemala', 'GTQ', 'es-GT'],
  ['GU', 'Guam', 'USD', 'en-GU'],
  ['GW', 'Guinea-Bissau', 'XOF', 'pt-GW'],
  ['GY', 'Guyana', 'GYD', 'en-GY'],
  ['HK', 'Hong Kong', 'HKD', 'zh-HK'],
  ['HN', 'Honduras', 'HNL', 'es-HN'],
  ['HR', 'Croatia', 'EUR', 'hr-HR'],
  ['HT', 'Haiti', 'HTG', 'fr-HT'],
  ['HU', 'Hungary', 'HUF', 'hu-HU'],
  ['ID', 'Indonesia', 'IDR', 'id-ID'],
  ['IE', 'Ireland', 'EUR', 'en-IE'],
  ['IL', 'Israel', 'ILS', 'he-IL'],
  ['IM', 'Isle of Man', 'GBP', 'en-IM'],
  ['IN', 'India', 'INR', 'en-IN'],
  ['IO', 'British Indian Ocean Territory', 'USD', 'en-IO'],
  ['IQ', 'Iraq', 'IQD', 'ar-IQ'],
  ['IR', 'Iran', 'IRR', 'fa-IR'],
  ['IS', 'Iceland', 'ISK', 'is-IS'],
  ['IT', 'Italy', 'EUR', 'it-IT'],
  ['JE', 'Jersey', 'GBP', 'en-JE'],
  ['JM', 'Jamaica', 'JMD', 'en-JM'],
  ['JO', 'Jordan', 'JOD', 'ar-JO'],
  ['JP', 'Japan', 'JPY', 'ja-JP'],
  ['KE', 'Kenya', 'KES', 'en-KE'],
  ['KG', 'Kyrgyzstan', 'KGS', 'ky-KG'],
  ['KH', 'Cambodia', 'KHR', 'km-KH'],
  ['KI', 'Kiribati', 'AUD', 'en-KI'],
  ['KM', 'Comoros', 'KMF', 'ar-KM'],
  ['KN', 'Saint Kitts and Nevis', 'XCD', 'en-KN'],
  ['KP', 'North Korea', 'KPW', 'ko-KP'],
  ['KR', 'South Korea', 'KRW', 'ko-KR'],
  ['KW', 'Kuwait', 'KWD', 'ar-KW'],
  ['KY', 'Cayman Islands', 'KYD', 'en-KY'],
  ['KZ', 'Kazakhstan', 'KZT', 'kk-KZ'],
  ['LA', 'Laos', 'LAK', 'lo-LA'],
  ['LB', 'Lebanon', 'LBP', 'ar-LB'],
  ['LC', 'Saint Lucia', 'XCD', 'en-LC'],
  ['LI', 'Liechtenstein', 'CHF', 'de-LI'],
  ['LK', 'Sri Lanka', 'LKR', 'si-LK'],
  ['LR', 'Liberia', 'LRD', 'en-LR'],
  ['LS', 'Lesotho', 'LSL', 'en-LS'],
  ['LT', 'Lithuania', 'EUR', 'lt-LT'],
  ['LU', 'Luxembourg', 'EUR', 'fr-LU'],
  ['LV', 'Latvia', 'EUR', 'lv-LV'],
  ['LY', 'Libya', 'LYD', 'ar-LY'],
  ['MA', 'Morocco', 'MAD', 'ar-MA'],
  ['MC', 'Monaco', 'EUR', 'fr-MC'],
  ['MD', 'Moldova', 'MDL', 'ro-MD'],
  ['ME', 'Montenegro', 'EUR', 'sr-ME'],
  ['MF', 'Saint Martin', 'EUR', 'fr-MF'],
  ['MG', 'Madagascar', 'MGA', 'fr-MG'],
  ['MH', 'Marshall Islands', 'USD', 'en-MH'],
  ['MK', 'North Macedonia', 'MKD', 'mk-MK'],
  ['ML', 'Mali', 'XOF', 'fr-ML'],
  ['MM', 'Myanmar', 'MMK', 'my-MM'],
  ['MN', 'Mongolia', 'MNT', 'mn-MN'],
  ['MO', 'Macao', 'MOP', 'zh-MO'],
  ['MP', 'Northern Mariana Islands', 'USD', 'en-MP'],
  ['MQ', 'Martinique', 'EUR', 'fr-MQ'],
  ['MR', 'Mauritania', 'MRU', 'ar-MR'],
  ['MS', 'Montserrat', 'XCD', 'en-MS'],
  ['MT', 'Malta', 'EUR', 'mt-MT'],
  ['MU', 'Mauritius', 'MUR', 'en-MU'],
  ['MV', 'Maldives', 'MVR', 'dv-MV'],
  ['MW', 'Malawi', 'MWK', 'en-MW'],
  ['MX', 'Mexico', 'MXN', 'es-MX'],
  ['MY', 'Malaysia', 'MYR', 'ms-MY'],
  ['MZ', 'Mozambique', 'MZN', 'pt-MZ'],
  ['NA', 'Namibia', 'NAD', 'en-NA'],
  ['NC', 'New Caledonia', 'XPF', 'fr-NC'],
  ['NE', 'Niger', 'XOF', 'fr-NE'],
  ['NF', 'Norfolk Island', 'AUD', 'en-NF'],
  ['NG', 'Nigeria', 'NGN', 'en-NG'],
  ['NI', 'Nicaragua', 'NIO', 'es-NI'],
  ['NL', 'Netherlands', 'EUR', 'nl-NL'],
  ['NO', 'Norway', 'NOK', 'nb-NO'],
  ['NP', 'Nepal', 'NPR', 'ne-NP'],
  ['NR', 'Nauru', 'AUD', 'en-NR'],
  ['NU', 'Niue', 'NZD', 'en-NU'],
  ['NZ', 'New Zealand', 'NZD', 'en-NZ'],
  ['OM', 'Oman', 'OMR', 'ar-OM'],
  ['PA', 'Panama', 'PAB', 'es-PA'],
  ['PE', 'Peru', 'PEN', 'es-PE'],
  ['PF', 'French Polynesia', 'XPF', 'fr-PF'],
  ['PG', 'Papua New Guinea', 'PGK', 'en-PG'],
  ['PH', 'Philippines', 'PHP', 'en-PH'],
  ['PK', 'Pakistan', 'PKR', 'ur-PK'],
  ['PL', 'Poland', 'PLN', 'pl-PL'],
  ['PM', 'Saint Pierre and Miquelon', 'EUR', 'fr-PM'],
  ['PN', 'Pitcairn Islands', 'NZD', 'en-PN'],
  ['PR', 'Puerto Rico', 'USD', 'es-PR'],
  ['PS', 'Palestine', 'ILS', 'ar-PS'],
  ['PT', 'Portugal', 'EUR', 'pt-PT'],
  ['PW', 'Palau', 'USD', 'en-PW'],
  ['PY', 'Paraguay', 'PYG', 'es-PY'],
  ['QA', 'Qatar', 'QAR', 'ar-QA'],
  ['RE', 'Réunion', 'EUR', 'fr-RE'],
  ['RO', 'Romania', 'RON', 'ro-RO'],
  ['RS', 'Serbia', 'RSD', 'sr-RS'],
  ['RU', 'Russia', 'RUB', 'ru-RU'],
  ['RW', 'Rwanda', 'RWF', 'rw-RW'],
  ['SA', 'Saudi Arabia', 'SAR', 'ar-SA'],
  ['SB', 'Solomon Islands', 'SBD', 'en-SB'],
  ['SC', 'Seychelles', 'SCR', 'en-SC'],
  ['SD', 'Sudan', 'SDG', 'ar-SD'],
  ['SE', 'Sweden', 'SEK', 'sv-SE'],
  ['SG', 'Singapore', 'SGD', 'en-SG'],
  ['SH', 'Saint Helena', 'SHP', 'en-SH'],
  ['SI', 'Slovenia', 'EUR', 'sl-SI'],
  ['SJ', 'Svalbard and Jan Mayen', 'NOK', 'nb-SJ'],
  ['SK', 'Slovakia', 'EUR', 'sk-SK'],
  ['SL', 'Sierra Leone', 'SLE', 'en-SL'],
  ['SM', 'San Marino', 'EUR', 'it-SM'],
  ['SN', 'Senegal', 'XOF', 'fr-SN'],
  ['SO', 'Somalia', 'SOS', 'so-SO'],
  ['SR', 'Suriname', 'SRD', 'nl-SR'],
  ['SS', 'South Sudan', 'SSP', 'en-SS'],
  ['ST', 'São Tomé and Príncipe', 'STN', 'pt-ST'],
  ['SV', 'El Salvador', 'USD', 'es-SV'],
  ['SX', 'Sint Maarten', 'ANG', 'nl-SX'],
  ['SY', 'Syria', 'SYP', 'ar-SY'],
  ['SZ', 'Eswatini', 'SZL', 'en-SZ'],
  ['TC', 'Turks and Caicos Islands', 'USD', 'en-TC'],
  ['TD', 'Chad', 'XAF', 'fr-TD'],
  ['TG', 'Togo', 'XOF', 'fr-TG'],
  ['TH', 'Thailand', 'THB', 'th-TH'],
  ['TJ', 'Tajikistan', 'TJS', 'tg-TJ'],
  ['TK', 'Tokelau', 'NZD', 'en-TK'],
  ['TL', 'Timor-Leste', 'USD', 'pt-TL'],
  ['TM', 'Turkmenistan', 'TMT', 'tk-TM'],
  ['TN', 'Tunisia', 'TND', 'ar-TN'],
  ['TO', 'Tonga', 'TOP', 'en-TO'],
  ['TR', 'Turkey', 'TRY', 'tr-TR'],
  ['TT', 'Trinidad and Tobago', 'TTD', 'en-TT'],
  ['TV', 'Tuvalu', 'AUD', 'en-TV'],
  ['TW', 'Taiwan', 'TWD', 'zh-TW'],
  ['TZ', 'Tanzania', 'TZS', 'sw-TZ'],
  ['UA', 'Ukraine', 'UAH', 'uk-UA'],
  ['UG', 'Uganda', 'UGX', 'en-UG'],
  ['US', 'United States', 'USD', 'en-US'],
  ['UY', 'Uruguay', 'UYU', 'es-UY'],
  ['UZ', 'Uzbekistan', 'UZS', 'uz-UZ'],
  ['VA', 'Vatican City', 'EUR', 'it-VA'],
  ['VC', 'Saint Vincent and the Grenadines', 'XCD', 'en-VC'],
  ['VE', 'Venezuela', 'VES', 'es-VE'],
  ['VG', 'British Virgin Islands', 'USD', 'en-VG'],
  ['VI', 'U.S. Virgin Islands', 'USD', 'en-VI'],
  ['VN', 'Vietnam', 'VND', 'vi-VN'],
  ['VU', 'Vanuatu', 'VUV', 'fr-VU'],
  ['WF', 'Wallis and Futuna', 'XPF', 'fr-WF'],
  ['WS', 'Samoa', 'WST', 'en-WS'],
  ['XK', 'Kosovo', 'EUR', 'sq-XK'],
  ['YE', 'Yemen', 'YER', 'ar-YE'],
  ['YT', 'Mayotte', 'EUR', 'fr-YT'],
  ['ZA', 'South Africa', 'ZAR', 'en-ZA'],
  ['ZM', 'Zambia', 'ZMW', 'en-ZM'],
  ['ZW', 'Zimbabwe', 'ZWL', 'en-ZW'],
];

export const COUNTRIES: CountryInfo[] = raw
  .map(([code, name, currency, locale]) => ({ code, name, currency, locale, flag: cc(code) }))
  .sort((a, b) => a.name.localeCompare(b.name));

export const COUNTRY_BY_CODE: Record<string, CountryInfo> = Object.fromEntries(
  COUNTRIES.map((c) => [c.code, c])
);

export const DEFAULT_COUNTRY = COUNTRY_BY_CODE.US;

// Detect country from browser locale (e.g. "en-IN" -> "IN"). Fallback to US.
export const detectCountryCode = (): string => {
  try {
    const langs = [navigator.language, ...(navigator.languages || [])];
    for (const l of langs) {
      const m = l.match(/[-_]([A-Za-z]{2})$/);
      if (m) {
        const code = m[1].toUpperCase();
        if (COUNTRY_BY_CODE[code]) return code;
      }
    }
    // Timezone-based fallback for a few common cases
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone || '';
    if (tz.includes('Kolkata') || tz.includes('Calcutta')) return 'IN';
  } catch {
    // ignore
  }
  return 'US';
};
